AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: JWTTokenExample
        Authorizers:
          JWTTokenExample: 
            JwtConfiguration:
              issuer: "XXX"
              audience: 
                - "https://auth0-jwt-authorizer"
            IdentitySource: "$request.header.Authorization"  

  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: nodejs12.x
      CodeUri: ./hello
      Events:
        HelloAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /hello
            Method: GET